if(HSO_LAYOUT_LOADED)
  return()
  endif()

  # --- Engine Root ---
  set(HSO_ROOT_DIR              "${CMAKE_SOURCE_DIR}" CACHE INTERNAL "" FORCE)
  set(HSO_VERSION_FILE          "${HSO_ROOT_DIR}/VERSION" CACHE INTERNAL "" FORCE)

  # --- Source & Infrastructure ---
  set(HSO_SRC_DIR               "${HSO_ROOT_DIR}/src" CACHE INTERNAL "" FORCE)
  set(HSO_INC_DIR               "${HSO_ROOT_DIR}/include" CACHE INTERNAL "" FORCE)
  set(HSO_PROG_DIR              "${HSO_ROOT_DIR}/programs" CACHE INTERNAL "" FORCE)
  set(HSO_DEV_TOOLS_DIR         "${HSO_ROOT_DIR}/devtools" CACHE INTERNAL "" FORCE)
  set(HSO_DOCS_DIR              "${HSO_ROOT_DIR}/docs" CACHE INTERNAL "" FORCE)

  # --- Asset Management ---
  set(HSO_ASSETS_DIR            "${HSO_ROOT_DIR}/assets" CACHE INTERNAL "" FORCE)
  set(HSO_DATA_DIR              "${HSO_ASSETS_DIR}/data" CACHE INTERNAL "" FORCE)
  set(HSO_GRIDS_DIR             "${HSO_ASSETS_DIR}/grids" CACHE INTERNAL "" FORCE)

  # --- Execution Workspace (Run Tree) ---
  set(HSO_RUN_DIR               "${HSO_ROOT_DIR}/run" CACHE INTERNAL "" FORCE)
  set(HSO_RUN_INPUT_DIR         "${HSO_RUN_DIR}/input" CACHE INTERNAL "" FORCE)
  set(HSO_RUN_OUTPUT_DIR        "${HSO_RUN_DIR}/results" CACHE INTERNAL "" FORCE)
  set(HSO_RUN_TMP_DIR           "${HSO_RUN_DIR}/results/tmp" CACHE INTERNAL "" FORCE)
  set(HSO_RUN_SCRIPTS_DIR       "${HSO_RUN_DIR}/scripts" CACHE INTERNAL "" FORCE)
  set(HSO_RUN_PLOT_DIR          "${HSO_RUN_SCRIPTS_DIR}/gnufiles" CACHE INTERNAL "" FORCE)

  # --- Testing Infrastructure ---
  set(HSO_TEST_DIR              "${HSO_ROOT_DIR}/tests" CACHE INTERNAL "" FORCE)
  set(HSO_TEST_HELPER_FILE      "${HSO_TEST_DIR}/helpers.sh" CACHE INTERNAL "" FORCE)
  set(HSO_TEST_SV_DIR           "${HSO_TEST_DIR}/system_validation" CACHE INTERNAL "" FORCE)

  # --- Static Analysis Sub-Layout ---
  set(HSO_TEST_SA_DIR           "${HSO_TEST_DIR}/static_analysis" CACHE INTERNAL "" FORCE)
  set(HSO_TEST_SA_HELPER_FILE   "${HSO_TEST_SA_DIR}/get_global_functions.sh" CACHE INTERNAL "" FORCE)
  set(HSO_REG_GLOBALS_DIR       "${HSO_TEST_SA_DIR}/baseline/${CMAKE_BUILD_TYPE}" CACHE INTERNAL "" FORCE)
  set(HSO_REG_GLOBALS_FILE      "${HSO_REG_GLOBALS_DIR}/global_registry.sym" CACHE INTERNAL "" FORCE)
  set(HSO_REG_GLOBALS_APP_FILE  "${HSO_REG_GLOBALS_DIR}/global_registry_app.sym" CACHE INTERNAL "" FORCE)

  # --- System Validation Sub-Layout ---
  set(HSO_TEST_SV_INPUT_DIR     "${HSO_TEST_SV_DIR}/input" CACHE INTERNAL "" FORCE)
  set(HSO_TEST_SV_EXPECT_DIR    "${HSO_TEST_SV_DIR}/expected" CACHE INTERNAL "" FORCE)
  set(HSO_TEST_SV_SCRIPTS_DIR   "${HSO_TEST_SV_DIR}/scripts" CACHE INTERNAL "" FORCE)


  # --- Build & Audit   ---
  set(HSO_BUILD_DIR             "${CMAKE_BINARY_DIR}" CACHE INTERNAL "" FORCE)
  set(HSO_EXEC_DIR              "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}" CACHE INTERNAL "" FORCE)
  set(HSO_AUDIT_DIR             "${HSO_BUILD_DIR}/audit" CACHE INTERNAL "" FORCE)
  set(HSO_BUILD_CONFIG          "${CMAKE_BUILD_TYPE}" CACHE INTERNAL "" FORCE)

  # --- Environment ---
  set(HSO_ENV_BLOCK
  "HSO_ROOT_DIR=${HSO_ROOT_DIR}"
  "HSO_VERSION_FILE=${HSO_VERSION_FILE}"
  "HSO_SRC_DIR=${HSO_SRC_DIR}"
  "HSO_INC_DIR=${HSO_INC_DIR}"
  "HSO_PROG_DIR=${HSO_PROG_DIR}"
  "HSO_DEV_TOOLS_DIR=${HSO_DEV_TOOLS_DIR}"
  "HSO_DOCS_DIR=${HSO_DOCS_DIR}"
  "HSO_ASSETS_DIR=${HSO_ASSETS_DIR}"
  "HSO_DATA_DIR=${HSO_DATA_DIR}"
  "HSO_GRIDS_DIR=${HSO_GRIDS_DIR}"
  "HSO_RUN_DIR=${HSO_RUN_DIR}"
  "HSO_RUN_INPUT_DIR=${HSO_RUN_INPUT_DIR}"
  "HSO_RUN_OUTPUT_DIR=${HSO_RUN_OUTPUT_DIR}"
  "HSO_RUN_SCRIPTS_DIR=${HSO_RUN_SCRIPTS_DIR}"
  "HSO_RUN_PLOT_DIR=${HSO_RUN_PLOT_DIR}"
  "HSO_TEST_DIR=${HSO_TEST_DIR}"
  "HSO_TEST_HELPER_FILE=${HSO_TEST_HELPER_FILE}"
  "HSO_TEST_SA_DIR=${HSO_TEST_SA_DIR}"
  "HSO_TEST_SA_HELPER_FILE=${HSO_TEST_SA_HELPER_FILE}"
  "HSO_TEST_SV_DIR=${HSO_TEST_SV_DIR}"
  "HSO_REG_GLOBALS_DIR=${HSO_REG_GLOBALS_DIR}"
  "HSO_REG_GLOBALS_FILE=${HSO_REG_GLOBALS_FILE}"
  "HSO_REG_GLOBALS_APP_FILE=${HSO_REG_GLOBALS_APP_FILE}"
  "HSO_TEST_SV_INPUT_DIR=${HSO_TEST_SV_INPUT_DIR}"
  "HSO_TEST_SV_EXPECT_DIR=${HSO_TEST_SV_EXPECT_DIR}"
  "HSO_TEST_SV_SCRIPTS_DIR=${HSO_TEST_SV_SCRIPTS_DIR}"
  "HSO_EXEC_DIR=${HSO_EXEC_DIR}"
  "HSO_BUILD_DIR=${HSO_BUILD_DIR}"
  "HSO_AUDIT_DIR=${HSO_AUDIT_DIR}"
  "HSO_BUILD_CONFIG=${HSO_BUILD_CONFIG}"
  CACHE INTERNAL "HSO environment"
  )

  set(HSO_LAYOUT_LOADED TRUE CACHE INTERNAL "HSO environment loaded.")
